"""
Django settings for apiforallmodules project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR,"template")
STATICFILES_DIR = BASE_DIR / "public" 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9@m=ys$ed7y6$6(c6$-fi+7%jup%#4zr1pbz$ho@7wc&gc(cg8'

SSL_CERTIFICATE = 'apiforallmodules/data.csr'
SSL_KEY = 'apiforallmodules/data.key'
SSL_REDIRECT = True


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SECURE_SSL_REDIRECT = False
ALLOWED_HOSTS = ['apnamd.in','alb-apnamd-ext-440795844.ap-southeast-1.elb.amazonaws.com','*']

GOOGLE_ANALYTICS_KEY ="G-X213RQS5KT"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
    'AnxietyTest',
    'BiologicalAgeCalculation',
    'rest_framework',
    # 'knox',

    # 'django.contrib.sites',
    'allauth',
    'allauth.account',
    'sslserver',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',

    ]

# SITE_ID = 1
# SOCIALACCOUNT_LOGIN_ON_GET=True


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

     #custom social auth setting
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALSSSS = True
ROOT_URLCONF = 'apiforallmodules.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apiforallmodules.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'apnamd',
		'USER': 'admin',
		'PASSWORD': 'UzuS8nvBL!$4wgzu',
		'HOST':'dev-mysql-1.cfkoabf1oytj.ap-southeast-1.rds.amazonaws.com',
		'PORT':'3306',
	}
}

APPEND_SLASH=False
# DATABASES = {
#     "default": {
#         "ENGINE": "mssql",
#         "NAME": "medibot",
#         "USER": "admin",
#         "PASSWORD": "mysql1234",
#         "HOST": "http://dev-mysql-1.cfkoabf1oytj.ap-southeast-1.rds.amazonaws.com",
#         "PORT": "3306",
#         "DRIVER": "SQL Server Native Client 11.0",

#     },
# }

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_L10N = True

USE_TZ = True

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = [ os.path.join(BASE_DIR, 'public'), ]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'admin@apnamd.ai'
EMAIL_HOST_PASSWORD = "@India2022"
EMAIL_USE_TLS = True

FILE_UPLOAD_MAX_MEMORY_SIZE = 4086

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'knox.auth.TokenAuthentication',
    ]
}


AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

]



# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         }
#     }
# }

LOGIN_REDIRECT_URL='Anxiety_thanks'
