# Generated by Django 3.2.12 on 2022-09-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Age', models.CharField(max_length=100)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('created_Date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Height', models.CharField(max_length=5)),
                ('Weight', models.CharField(max_length=15)),
                ('BMI', models.CharField(max_length=5)),
                ('Sex', models.CharField(max_length=15)),
                ('Diabetes', models.CharField(max_length=100)),
                ('Hypertension', models.CharField(max_length=100)),
                ('Heart_disease', models.CharField(max_length=100)),
                ('Strokes', models.CharField(max_length=100)),
                ('History_of_4', models.CharField(max_length=100)),
                ('Smoke', models.CharField(max_length=100)),
                ('Alcohol', models.CharField(max_length=100)),
                ('Exercise', models.CharField(max_length=100)),
                ('Calories_count', models.CharField(max_length=100)),
                ('Age_90_years', models.CharField(max_length=100)),
                ('Covid_history', models.CharField(max_length=100)),
                ('UniqueID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clientid')),
            ],
        ),
    ]
