# Generated by Django 3.2.12 on 2022-09-15 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_riskid_uniqueid'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskid',
            name='Unique_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.clientid'),
            preserve_default=False,
        ),
    ]
