# Generated by Django 3.2.12 on 2022-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_clientid_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientid',
            name='Email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
