# Generated by Django 3.2.12 on 2022-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_basic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basic',
            old_name='Medication',
            new_name='Email',
        ),
        migrations.AddField(
            model_name='basic',
            name='Covid',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='basic',
            name='Suffering_Duration',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='basic',
            name='Unique_ID',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
