# Generated by Django 3.2.12 on 2022-10-07 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20221006_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cough',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Qn2A', models.CharField(blank=True, max_length=15)),
                ('Qn2B', models.CharField(blank=True, max_length=15)),
                ('Qn2C', models.CharField(blank=True, max_length=15)),
                ('Qn2D', models.CharField(blank=True, max_length=15)),
                ('Qn2E', models.CharField(blank=True, max_length=5)),
                ('Qn2F', models.CharField(blank=True, max_length=15)),
                ('Qn2G', models.CharField(blank=True, max_length=15)),
                ('Qn2H', models.CharField(blank=True, max_length=15)),
                ('Qn2I', models.CharField(blank=True, max_length=15)),
                ('Qn2J', models.CharField(blank=True, max_length=15)),
                ('Qn2K', models.CharField(blank=True, max_length=15)),
                ('Qn2L', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.basic')),
            ],
        ),
    ]
