# Generated by Django 3.2.12 on 2022-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_cough'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Visit_Type', models.CharField(blank=True, max_length=15)),
                ('Visit_Date', models.CharField(blank=True, max_length=15)),
                ('Visit_Time', models.CharField(blank=True, max_length=15)),
                ('Medical', models.CharField(blank=True, max_length=15)),
                ('Nursing', models.CharField(blank=True, max_length=5)),
                ('Admin', models.CharField(blank=True, max_length=15)),
                ('Practice_Cleanliness', models.CharField(blank=True, max_length=15)),
                ('Comment', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
