# Generated by Django 3.2.12 on 2022-10-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='overall_detail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Qn', models.CharField(blank=True, max_length=15)),
                ('Ans', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.basic')),
            ],
        ),
    ]
