# Generated by Django 3.2.12 on 2022-10-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_overall_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_detail',
            name='module_name',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
