# Generated by Django 3.2.12 on 2022-10-18 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_overall_detail_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_detail',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
