# Generated by Django 3.2.12 on 2022-10-19 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_special_doc_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_doc_detail',
            name='recevingdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
