# Generated by Django 3.2.12 on 2022-11-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_special_doc_detail_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overall_detail',
            name='Ans',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='overall_detail',
            name='Qn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='overall_detail',
            name='module_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
