# Generated by Django 3.2.12 on 2022-11-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_nutrient_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrient_Information',
        ),
    ]
