# Generated by Django 3.2.12 on 2022-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_delete_nutrient_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT', models.CharField(max_length=250)),
                ('CATEGORY', models.CharField(max_length=250)),
                ('CALORIE', models.FloatField()),
                ('CARB', models.FloatField()),
                ('PRO', models.FloatField()),
                ('FAT', models.FloatField()),
                ('Ex_Swim', models.FloatField()),
                ('Ex_Jog', models.FloatField()),
                ('Ex_Cycle', models.FloatField()),
                ('Ex_Walk', models.FloatField()),
            ],
        ),
    ]
