# Generated by Django 3.2.12 on 2022-12-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_nutrient_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('Uploaded_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Unique_ID', models.CharField(blank=True, max_length=15)),
                ('DOB', models.CharField(blank=True, max_length=15)),
                ('Age', models.CharField(blank=True, max_length=15)),
                ('Sex', models.CharField(blank=True, max_length=15)),
                ('Email', models.CharField(blank=True, max_length=150)),
                ('phonenumber', models.CharField(blank=True, max_length=50)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skin_Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('Uploaded_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom_Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Qn', models.CharField(blank=True, max_length=15, null=True)),
                ('Ans', models.CharField(blank=True, max_length=15, null=True)),
                ('Module_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.id')),
            ],
        ),
        migrations.CreateModel(
            name='Risk_Factors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Height', models.CharField(blank=True, max_length=5)),
                ('Weight', models.CharField(blank=True, max_length=15)),
                ('BMI', models.CharField(blank=True, max_length=15)),
                ('Smoke', models.CharField(blank=True, max_length=15)),
                ('alcohol', models.CharField(blank=True, max_length=15)),
                ('Covid', models.CharField(blank=True, max_length=15)),
                ('Walk_daily', models.CharField(blank=True, max_length=15)),
                ('Weight_gain', models.CharField(blank=True, max_length=15)),
                ('Long_Life', models.CharField(blank=True, max_length=15)),
                ('Diabetes', models.CharField(blank=True, max_length=15)),
                ('Hypertension', models.CharField(blank=True, max_length=15)),
                ('Asthma', models.CharField(blank=True, max_length=15)),
                ('High_Cholesterol', models.CharField(blank=True, max_length=15)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.id')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.CharField(blank=True, max_length=15, null=True)),
                ('Module_Name', models.CharField(blank=True, max_length=15, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.id')),
            ],
        ),
    ]
