# Generated by Django 3.2.16 on 2022-12-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_disease_explaination_explainations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_explaination',
            name='diseasename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
