# Generated by Django 3.2.16 on 2022-12-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_alter_disease_explaination_diseasename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease_explaination',
            name='detailedname',
        ),
    ]
