# Generated by Django 3.2.16 on 2022-12-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_remove_disease_explaination_detailedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiciddetails',
            name='sender_id',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
