# Generated by Django 3.2.16 on 2022-12-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_basiciddetails_sender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease_detailswithid',
            name='user',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='modules_details',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
