# Generated by Django 3.2.16 on 2022-12-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20221221_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_detailswithid',
            name='sender_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
