# Generated by Django 3.2.16 on 2022-12-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_disease_detailswithid_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease_detailswithid',
            name='sender_id',
        ),
    ]
