# Generated by Django 3.2.16 on 2022-12-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_remove_disease_detailswithid_sender_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='disease_detailswithId',
            new_name='Diagnosis_Dec',
        ),
        migrations.RenameModel(
            old_name='BasicIdDetails',
            new_name='ID_Dec',
        ),
    ]
