# Generated by Django 3.2.16 on 2022-12-23 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20221223_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='id_dec',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
