# Generated by Django 3.2.16 on 2022-12-28 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_feedbackupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cough',
            name='user',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='disease_details',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='general_doc_detail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='overall_detail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='risk_factors',
            name='user',
        ),
        migrations.RemoveField(
            model_name='riskid',
            name='Unique_ID',
        ),
        migrations.RemoveField(
            model_name='special_doc_detail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='symptom_questions',
            name='user',
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 28, 6, 45, 19, 121375)),
        ),
        migrations.DeleteModel(
            name='Basic',
        ),
        migrations.DeleteModel(
            name='ClientID',
        ),
        migrations.DeleteModel(
            name='Cough',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='disease_details',
        ),
        migrations.DeleteModel(
            name='general_doc_detail',
        ),
        migrations.DeleteModel(
            name='ID',
        ),
        migrations.DeleteModel(
            name='overall_detail',
        ),
        migrations.DeleteModel(
            name='Risk_Factors',
        ),
        migrations.DeleteModel(
            name='RiskID',
        ),
        migrations.DeleteModel(
            name='special_doc_detail',
        ),
        migrations.DeleteModel(
            name='Symptom_Questions',
        ),
    ]
