# Generated by Django 3.2.16 on 2022-12-28 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis_Dec',
            fields=[
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disease', models.CharField(blank=True, max_length=15, null=True)),
                ('module_name', models.CharField(blank=True, max_length=15, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet_Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('Uploaded_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Disease_explaination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseasename', models.CharField(blank=True, max_length=200)),
                ('explainations', models.CharField(blank=True, max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='feedbackupdated',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('senderid', models.CharField(blank=True, max_length=150)),
                ('DiagnosticAccuracy', models.CharField(blank=True, max_length=15)),
                ('UserExperience', models.CharField(blank=True, max_length=15)),
                ('Likelihoodtorecommend', models.CharField(blank=True, max_length=15)),
                ('dateandtime', models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 28, 6, 48, 10, 636955))),
            ],
        ),
        migrations.CreateModel(
            name='ID_Dec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Unique_ID', models.CharField(blank=True, max_length=15)),
                ('sender_id', models.CharField(blank=True, max_length=1500)),
                ('DOB', models.CharField(blank=True, max_length=15)),
                ('Age', models.CharField(blank=True, max_length=15)),
                ('Sex', models.CharField(blank=True, max_length=15)),
                ('Height', models.CharField(blank=True, max_length=5)),
                ('Weight', models.CharField(blank=True, max_length=15)),
                ('BMI', models.CharField(blank=True, max_length=15)),
                ('Smoker', models.CharField(blank=True, max_length=15)),
                ('alcohal', models.CharField(blank=True, max_length=15)),
                ('phonenumber', models.CharField(blank=True, max_length=50)),
                ('Email', models.CharField(blank=True, max_length=150)),
                ('Covid', models.CharField(blank=True, max_length=15)),
                ('Suffering_Duration', models.CharField(blank=True, max_length=150)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='modules_details',
            fields=[
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Qn', models.CharField(blank=True, max_length=15, null=True)),
                ('Ans', models.CharField(blank=True, max_length=15, null=True)),
                ('module_name', models.CharField(blank=True, max_length=15, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRODUCT', models.CharField(max_length=250)),
                ('CATEGORY', models.CharField(max_length=250)),
                ('CALORIE', models.FloatField()),
                ('CARB', models.FloatField()),
                ('PRO', models.FloatField()),
                ('FAT', models.FloatField()),
                ('Ex_Swim', models.FloatField()),
                ('Ex_Jog', models.FloatField()),
                ('Ex_Cycle', models.FloatField()),
                ('Ex_Walk', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Skin_Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('Uploaded_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
