# Generated by Django 3.2.16 on 2023-01-02 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_feedbackupdated_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis_dec',
            name='disease',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis_dec',
            name='module_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis_dec',
            name='user',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='DiagnosticAccuracy',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='Likelihoodtorecommend',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='UserExperience',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 2, 4, 3, 53, 882377)),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='senderid',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Age',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='BMI',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Covid',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='DOB',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Email',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Sex',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Smoker',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Suffering_Duration',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Unique_ID',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='Weight',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='id_dec',
            name='alcohal',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='modules_details',
            name='Ans',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modules_details',
            name='Qn',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modules_details',
            name='module_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='modules_details',
            name='user',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
