# Generated by Django 3.2.16 on 2023-02-02 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230102_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message2WhatApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnosis_dec',
            name='disease',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 2, 3, 16, 8, 538017)),
        ),
    ]
