# Generated by Django 3.2.16 on 2023-03-01 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230202_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsappdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=1500, null=True)),
                ('discussion_point', models.CharField(max_length=100)),
                ('bloodresult', models.CharField(blank=True, max_length=1500, null=True)),
                ('otherresult', models.CharField(blank=True, max_length=150, null=True)),
                ('healthinsurance', models.CharField(blank=True, max_length=150, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 7, 40, 43, 963046)),
        ),
    ]
