# Generated by Django 3.2.16 on 2023-03-01 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230301_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappdata',
            name='diagnosis_detail',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 10, 46, 32, 149476)),
        ),
    ]
