# Generated by Django 3.2.16 on 2023-03-01 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20230301_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappdata',
            name='from_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 1, 11, 21, 0, 351630)),
        ),
        migrations.AlterField(
            model_name='whatsappdata',
            name='discussion_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
