# Generated by Django 3.2.16 on 2023-03-15 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_feedbackupdated_dateandtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 6, 38, 9, 811276)),
        ),
    ]
