# Generated by Django 3.2.16 on 2023-03-15 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_feedbackupdated_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryDta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=1500, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('Uploaded_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 6, 43, 40, 188541)),
        ),
    ]
