# Generated by Django 3.2.16 on 2023-03-22 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230315_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=1500, null=True)),
                ('from_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.CharField(blank=True, max_length=1500, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 22, 3, 30, 11, 706055)),
        ),
    ]
