# Generated by Django 3.2.16 on 2023-03-28 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20230322_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 28, 9, 25, 16, 438963)),
        ),
    ]
