# Generated by Django 3.2.16 on 2023-03-31 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20230329_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 31, 5, 25, 45, 811543)),
        ),
    ]
