# Generated by Django 3.2.16 on 2023-04-03 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_feedbackupdated_dateandtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules_details',
            name='uniqueis',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 4, 26, 52, 800311)),
        ),
    ]
