# Generated by Django 3.2.16 on 2023-04-03 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20230403_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='user',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 4, 37, 27, 189402)),
        ),
    ]
