# Generated by Django 3.2.16 on 2023-04-06 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20230406_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='modulename',
            field=models.CharField(blank=True, max_length=1500),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 6, 7, 36, 34, 361485)),
        ),
    ]
