# Generated by Django 3.2.16 on 2023-04-10 07:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0020_auto_20230406_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='smoking',
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='gender',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='height',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='number',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldetail',
            name='weight',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 10, 7, 58, 54, 801445)),
        ),
        migrations.CreateModel(
            name='medicaldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.CharField(blank=True, max_length=1500, null=True)),
                ('alcohal', models.CharField(blank=True, max_length=1500, null=True)),
                ('covid', models.CharField(blank=True, max_length=1500, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=1500, null=True)),
                ('hypertension', models.CharField(blank=True, max_length=1500, null=True)),
                ('asthama', models.CharField(blank=True, max_length=1500, null=True)),
                ('cholestrol', models.CharField(blank=True, max_length=1500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
