# Generated by Django 3.2.16 on 2023-04-11 05:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0021_auto_20230410_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsapp_medical_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoking', models.CharField(blank=True, max_length=1500, null=True)),
                ('alcohal', models.CharField(blank=True, max_length=1500, null=True)),
                ('covid', models.CharField(blank=True, max_length=1500, null=True)),
                ('diabetes', models.CharField(blank=True, max_length=1500, null=True)),
                ('hypertension', models.CharField(blank=True, max_length=1500, null=True)),
                ('asthama', models.CharField(blank=True, max_length=1500, null=True)),
                ('cholestrol', models.CharField(blank=True, max_length=1500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 11, 5, 5, 25, 440458)),
        ),
        migrations.DeleteModel(
            name='medicaldetail',
        ),
    ]
