# Generated by Django 3.2.16 on 2023-04-13 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20230411_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 13, 5, 1, 35, 180778)),
        ),
    ]
