# Generated by Django 3.2.16 on 2023-04-14 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_feedbackupdated_dateandtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=1500, null=True)),
                ('DOB', models.CharField(max_length=15)),
                ('Suffered_Medical_Condition', models.CharField(blank=True, max_length=1500, null=True)),
                ('Current_Medications', models.CharField(blank=True, max_length=100, null=True)),
                ('Doctor_Details', models.CharField(blank=True, max_length=1500, null=True)),
                ('Unique_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Chat_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telegram_Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('Diagnosis', models.CharField(blank=True, max_length=1500, null=True)),
                ('filedata', models.FileField(upload_to='images/')),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 14, 9, 12, 59, 858620)),
        ),
    ]
