# Generated by Django 3.2.16 on 2023-04-20 05:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0025_auto_20230414_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('Height', models.IntegerField(blank=True, null=True)),
                ('BMI', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Telegram_Data',
        ),
        migrations.DeleteModel(
            name='Telegram_Diagnosis',
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 20, 5, 16, 26, 543495)),
        ),
    ]
