# Generated by Django 3.2.16 on 2023-04-20 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20230420_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmidata',
            name='BMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 20, 6, 2, 48, 92576)),
        ),
    ]
