# Generated by Django 3.2.16 on 2023-04-20 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20230420_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmidata',
            name='BMI',
            field=models.CharField(blank=True, default=0, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 20, 7, 29, 57, 618462)),
        ),
    ]
