# Generated by Django 3.2.16 on 2023-05-04 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20230420_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentdataNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=1500, null=True)),
                ('appointmentdetails', models.TextField(blank=True, max_length=1500, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 4, 4, 27, 24, 847899)),
        ),
    ]
