# Generated by Django 3.2.16 on 2023-05-04 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20230504_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(blank=True, max_length=1500, null=True)),
                ('appointmentdata', models.CharField(blank=True, max_length=1500, null=True)),
                ('dateandtime', models.DateTimeField(blank=True)),
                ('DiagnosticAccuracy', models.CharField(blank=True, max_length=150)),
                ('UserExperience', models.CharField(blank=True, max_length=150)),
                ('Likelihoodtorecommend', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 4, 9, 37, 58, 617456)),
        ),
    ]
