# Generated by Django 3.2.16 on 2023-05-10 07:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20230504_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdatanew',
            name='appointmentdate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdatanew',
            name='appointmenttime',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdatanew',
            name='docname',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 10, 7, 20, 48, 952520)),
        ),
    ]
