# Generated by Django 3.2.16 on 2023-05-12 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20230510_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorbelongto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(blank=True, max_length=1500, null=True)),
                ('belongto', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedbackupdated',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 4, 28, 29, 538156)),
        ),
    ]
